### ISSUE TITLE
Save and restore open tabs

### ISSUE THREAD

**Issue by Thunderbottom** [balzathor/UltimateBrowserProject#40]
Restore last session tabs when application is re-opened. This will take a shared preference on how many tabs were open, and save a file with all the URL and then according to the number of pages in SP, we can start the URL(s) again. Or is there a better way to do that?

**Comment by james9909** [comment]
Would this be a feature that can be toggled in the settings?

**Comment by Thunderbottom** [comment]
Yeah, that would be better. But what I was saying is, Uh have you seen Chrome? When you close the application with certain tabs open, it automatically re-opens the tabs on the next run. It Should just function like that.

**Comment by james9909** [comment]
Ok I see

**Comment by james9909** [comment]
I've added a basic implementation, but the browser still opens up a blank tab as well as the saved tabs.

**Comment by Thunderbottom** [comment]
Does it work now?

**Comment by Thunderbottom** [comment]
Add a `SharedPreference` in settings just like for Fullscreen mode. Sometimes people would not like to Restore Last session tabs so that would be handy to switch in the settings.

**Comment by james9909** [comment]
Is there any way I can open a blank tab without pinning it? The only issue I've found was opening the previously opened tab when one of the tabs was blank.

**Comment by Thunderbottom** [comment]
When one of the tabs was blank, you can just open up a blank page, like when you do at start.

**Comment by Thunderbottom** [comment]
And currently you can only pin albums

**Comment by james9909** [comment]
I can add albums with a url, in which they load in the background, but opening a blank home album loads it in the front. You can see what I mean by trying to restore blank tabs mixed with actual tabs. It will show set the blank tab as the current tab instead of the actual one.

**Comment by Thunderbottom** [comment]
Just do not show blank page if there is any when links were open in the last session.

**Comment by Thunderbottom** [comment]
Top omnibox animation looks pretty nice, can you hide the omnibox when you scroll down for bottom omnibox too? I suppose no one would scroll up just to hide the omnibox from bottom, its just meaningless.

**Comment by Thunderbottom** [comment]
Also, you can then just set bottom animation just as top :)

**Comment by Thunderbottom** [comment]
White space is shown on all webpages when the omnibox is at the bottom.

**Comment by james9909** [comment]
Have you tested this out yet?

**Comment by Thunderbottom** [comment]
No, I'm talking about the hiding/viewing omnibox on bottom part of the page, will test this one by that time :)

**Comment by james9909** [comment]
Alright let me get this completely working then I'll check out other stuff

**Comment by takahirom** [comment]
Sorry , It might be my bug ...
I will look tomorrow or day after tomorrow.
Sorry to trouble you ,If you can fix , please fix..
I think reason is here.
https://github.com/balzathor/UltimateBrowserProject/blob/master/app/src/main/java/io/github/UltimateBrowserProject/Unit/ViewUnit.java#L22-22

**Comment by james9909** [comment]
If I don't open blank tabs, then it works fine, but do you want to restore blank tabs?

**Comment by Thunderbottom** [comment]
Why would you restore blank tabs? they can make a new one if they want to

**Comment by james9909** [comment]
Alright cool

**Comment by james9909** [comment]
Anyone else want to test it before I merge?

**Comment by Thunderbottom** [comment]
If its done, you can merge it with the main repo so I can test it and release the first Beta tomorrow maybe. Still waiting on you to fix the bottom omnibox :D You did a great job!

**Comment by Thunderbottom** [comment]
You can merge it, if its not fine we can just revert the PR, which is totally fine for now

**Comment by james9909** [comment]
So hiding the bottom omnibox should work like hiding the top one?

**Comment by Thunderbottom** [comment]
Yeah, scrolling down on a page should hide it instead of scrolling top. Also, tweaking the animation just like the top would be great

**Comment by james9909** [comment]
okay :)

**Comment by Thunderbottom** [comment]
Is that possible?

**Comment by Thunderbottom** [comment]
There's a white box that appears on the bottom, fix that too, idk where that came from.

**Comment by james9909** [comment]
idk I'll look at it after making sure my merge is good

**Comment by davimount** [comment]
I don't know where is the origin of that, but omnibox is null when going back to home and if you scroll it will crash :S

```
java.lang.NullPointerException: Attempt to invoke virtual method 'int android.widget.RelativeLayout.getVisibility()' on a null object reference
            at io.github.UltimateBrowserProject.View.SwitcherPanel.onInterceptTouchEvent(SwitcherPanel.java:370)
[...]
```

**Comment by Thunderbottom** [comment]
Check SwitcherPanel.class line 370, you'll get what's wrong

**Comment by james9909** [comment]
The only difference between the bottom and top animations is that when the omnibox is on top, I add it to the content frame, and then bring it to the front, so it doesn't show the black background when hiding. However, if I do this for the bottom omnibox, the animation breaks. Still looking into it.

**Comment by Thunderbottom** [comment]
Isn't there any other way to do that?

**Comment by james9909** [comment]
I think it's because when I add the view, the omnibox appears at the top.

**Comment by Thunderbottom** [comment]
Do the same to the bottom then, if that works for top it should for bottom too

**Comment by james9909** [comment]
Using the same method to bring the omnibox to the front does not work for the bottom as it does for the top. You can check it out over <a href="https://github.com/balzathor/UltimateBrowserProject/blob/master/app/src/main/java/io/github/UltimateBrowserProject/Activity/BrowserActivity.java#L2092">here</a>.

**Comment by Thunderbottom** [comment]
At least get rid of that white box that shows up, also, switch the animation to hide when scrolling from top to bottom

**Comment by Thunderbottom** [comment]
I'll check that later, have some machine learning stuff going on at this moment! :D

**Comment by takahirom** [comment]
Maybe, I fixed white space bug.
I committed to "master" branch.
https://github.com/balzathor/UltimateBrowserProject/issues/40#issuecomment-121293077

**Comment by Thunderbottom** [comment]
I'll try it and check it out whether it happens :)

**Comment by Thunderbottom** [comment]
@takahirom it seems to be fixed, good job on that :D @james9909 Are you done with fixing the Bottom Omnibox animations?

**Comment by james9909** [comment]
The scrolling motion to hide and show the omniboxes are the same, but I still have the same background problem when hiding the bottom omnibox.

**Comment by Thunderbottom** [comment]
Can you just make it to hide the omnibox when you scroll down instead of scrolling to the top?

**Comment by james9909** [comment]
its done

**Comment by Thunderbottom** [comment]
Nice, I'll test it, then Deploy the first beta. Good job :)
I'll start development on my part when I'm done with learning Python.
